// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb-cF5x5ic45f86t2hVjF5GKmOMqLVvoU',
    appId: '1:377717585527:web:6f6b33f0133bf56d30f872',
    messagingSenderId: '377717585527',
    projectId: 'course-d9b57',
    authDomain: 'course-d9b57.firebaseapp.com',
    storageBucket: 'course-d9b57.appspot.com',
    measurementId: 'G-9NZHXGNGK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkd2HsAzKbfXAfI87E7aPlzYOK6B7iS0U',
    appId: '1:377717585527:android:c309cacf8e2e2afb30f872',
    messagingSenderId: '377717585527',
    projectId: 'course-d9b57',
    storageBucket: 'course-d9b57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL2rT4orb8fpH7mirTAJGEDKVsg1x77Z4',
    appId: '1:377717585527:ios:0edd73182203d6b630f872',
    messagingSenderId: '377717585527',
    projectId: 'course-d9b57',
    storageBucket: 'course-d9b57.appspot.com',
    iosClientId: '377717585527-cmu79joffbi2g933d4mbis6gcsbnefu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL2rT4orb8fpH7mirTAJGEDKVsg1x77Z4',
    appId: '1:377717585527:ios:1f938797c80b1da530f872',
    messagingSenderId: '377717585527',
    projectId: 'course-d9b57',
    storageBucket: 'course-d9b57.appspot.com',
    iosClientId: '377717585527-0cuhcb0q530pj05musv9nqjptbqrcifk.apps.googleusercontent.com',
    iosBundleId: 'com.example.course.RunnerTests',
  );
}
