// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBreDhW_3ACMxKUn50cmqClQG-yvh-mWMA',
    appId: '1:1079271870254:web:cb7f2fee07e9b81d7734bf',
    messagingSenderId: '1079271870254',
    projectId: 'courseapp-df70f',
    authDomain: 'courseapp-df70f.firebaseapp.com',
    databaseURL: 'https://courseapp-df70f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseapp-df70f.appspot.com',
    measurementId: 'G-8F1SN2ZLBN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCcK86ErKsfsmzsQZZrHhcO5uscTf0gOw',
    appId: '1:1079271870254:android:638a6f405bacf04c7734bf',
    messagingSenderId: '1079271870254',
    projectId: 'courseapp-df70f',
    databaseURL: 'https://courseapp-df70f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseapp-df70f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgfaxrdre98F6z6q-Vub6OPMSDVPAEnl4',
    appId: '1:1079271870254:ios:20a0da9800a512107734bf',
    messagingSenderId: '1079271870254',
    projectId: 'courseapp-df70f',
    databaseURL: 'https://courseapp-df70f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseapp-df70f.appspot.com',
    iosClientId: '1079271870254-6a73hcsucgu21904mmfslgtr6vbib3h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgfaxrdre98F6z6q-Vub6OPMSDVPAEnl4',
    appId: '1:1079271870254:ios:802e94244640806d7734bf',
    messagingSenderId: '1079271870254',
    projectId: 'courseapp-df70f',
    databaseURL: 'https://courseapp-df70f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'courseapp-df70f.appspot.com',
    iosClientId: '1079271870254-ob6014m6ckuqgf525794tlcp5ede1g2m.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseapp.RunnerTests',
  );
}
